config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_up: 'register',
      sign_out: 'logout',
    },
  )

  # custom routes
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  # resources routes
  resources :portfolios, except: [:show]
  resources :blogs do
    member { get :toggle_status }
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId

  enum status: { draft: 0, published: 1 }
  friendly_id :title, use: :slugged

  # associations
  belongs_to :topic

  # validations
  validates_presence_of :title, :body
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]
  layout 'blog'
  access(
    all: %i[show index],
    user: {
      except: %i[new create edit update destroy toggle_status],
    },
    site_admin: :all,
  )

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = 'My Blogs'
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @page_title = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html do
          redirect_to blog_url(@blog), notice: 'Blog was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html do
          redirect_to blog_url(@blog), notice: 'Blog was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html do
        redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <p class="blog-post-meta"><%= time_ago_in_words(blog.created_at) %> ago</p>
  <p class="blog-post-meta">
    <%  if logged_in?(:site_admin) %>
      <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
      |
      <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
      |
      <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
  </p>
  <p><%= blog.body %></p>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: 15  %>
  </div>
  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<%= paginate @blogs %>
<%= render @blogs %>
<%= paginate @blogs %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<h2>  <%= @blog.title %></h2>
<%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %> | <%= link_to 'Back', blogs_path %>
<p><%= @blog.body %> </p>