config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_up: 'register',
      sign_out: 'logout',
    },
  )

  # custom routes
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  # resources routes
  resources :portfolios, except: [:show]
  resources :blogs do
    member { get :toggle_status }
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  # associations
  has_many :technologies

  # nested_attr
  accepts_nested_attributes_for(
    :technologies,
    reject_if: lambda { |attr| attr['name'].blank? },
  )

  # validations
  validates_presence_of :title, :body, :main_image, :thumb_image

  # scopes
  def self.angular
    where(subtitle: 'Angular')
  end

  scope :by_position, -> { order(position: :asc) }
  scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

  # callbacks
  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '300')
    self.thumb_image ||=
      Placeholder.image_generator(height: '300', width: '200')
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, except: %i[index new create angular]
  layout 'portfolio'
  access(
    all: %i[show index],
    user: {
      except: %i[new create edit update destroy],
    },
    site_admin: :all,
  )

  def index
    @portfolio_items = Portfolio.by_position
  end

  def angular
    @angular = Portfolio.angular
  end

  def show; end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    if @portfolio_item.save
      redirect_to portfolios_path, notice: 'Portfolio created successfully!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @portfolio_item.update(portfolio_params)
      redirect_to portfolios_path, notice: 'Portfolio updated sucessfully!'
    else
      render 'edit'
    end
  end

  def destroy
    @portfolio_item.destroy
    redirect_to portfolios_path, notice: 'Portfolio removed!'
  end

  private

  def portfolio_params
    params
      .required(:portfolio)
      .permit(:title, :subtitle, :body, technologies_attributes: [:name])
  end

  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control"  %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 13  %>
      </div>
    </div>
    <div class="col-md-12">
      <hr>
      <h3>Technologies Used:</h3>
      <div>
        <%= f.fields_for(:technologies) do |tf| %>
          <div class="form-group">
            <%= tf.label :name%>
            <%= tf.text_field :name, class: "form-control"  %>
          </div>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.submit "Save Portfolio Item", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 box-shadow">
    <p><%= image_tag portfolio_item.thumb_image, class: "card-img-top" unless portfolio_item.thumb_image.nil?%></p>
    <div class="card-body">
      <p class="card-text">
        <span>
          <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
        </span>
        <%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to "Edit", edit_portfolio_path(portfolio_item), class: "btn btn-sm btn-outline-secondary" if logged_in?(:site_admin) %>
          <%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-danger" if logged_in?(:site_admin) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<%= link_to "Create new Item", new_portfolio_path %>
<h1>Angular Portfolio Items</h1>
<% @angular.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <p><%= portfolio_item.main_image %></p>
  <p><%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%></p>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) %>
  <%= link_to "Delete Portfolio", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit a portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<%= link_to "Create new Item", new_portfolio_path if logged_in?(:site_admin) %>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <%= render partial: "portfolio_item", collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <hr>
      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies do |technology| %>
        <p><%= technology.name %></p>
      <% end %>
    </div>
  </div>
</div>