config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_up: 'register',
      sign_out: 'logout',
    },
  )

  # custom routes
  root to: 'pages#home'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular-items', to: 'portfolios#angular'

  # resources routes
  resources :portfolios, except: [:show]
  resources :blogs do
    member { get :toggle_status }
  end
end

app/views/shared/_application_footer.html.erb
   
<div class="mastfoot">
  <div class="inner">
    <p><%= set_copyright %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Nana Quam</h3>
    <nav class="nav masthead-nav">
      <%= nav_helper("span", "nav-link") %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= set_copyright %></p>
  <p><a href="#">Back to top</a></p>
  <hr>
</footer>

app/views/shared/_blog_header.html.erb
     
<div class="blog-header">
  <h1 class="blog-title">My Blog</h1>
  <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
  <%= link_to 'Write A New Blog', new_blog_path if logged_in?(:site_admin)%>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="blog-nav">
      <%= nav_helper("span", "blog-nav-item") %>
      <%= login_helper("blog-nav-item") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Portfolios", portfolios_path %></div>
  <div><%= link_to "Blogs", blogs_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View Portfolios", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= set_copyright %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">
      Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.
    </p>
    <p>
      <%= link_to "Find More About Me", about_me_path, class: "btn btn-primary my-2" %>
      <%= link_to "My Blog Page", blogs_path, class: "btn btn-outline-secondary" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">Nana Quam</h4>
        <p class="text-muted">
          Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.
        </p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore:</h4>
        <ul class="list-unstyled">
          <%= nav_helper("li", "text-white") %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark box-shadow">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>Nana Quam</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>